Todolist project
Design-and-Code/Quick-projects pull request #21
Opened 2022-10-10 18:11 UTC by SumitKanth

> **Note** to the contributors:
>
> Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](/CONTRIBUTING.md) file first.

## What kind of change does this PR introduce? (select / add custom
new project

## Description 
Added todolist project, made on react. In this user can write there Todos, if they want to update their Todo they can do that also and also delete the todo. 

## Checklist
> mark `[X]` to make it checked.

- [x] I've read the contribution guidelines.
- [ ] I've mentioned my project in the Readme as per guidelines.
- [x] I've checked that my project is not a duplicate project and I have cross checked the exisiting projects in this repository.

## Related Issues
Fixes Issue #7

2022-10-10 18:17 UTC, Greeshma2903 commented
Awesome! Can you mention your project details in the Readme? (underneath Project List section)

2022-10-10 18:39 UTC, SumitKanth commented
> Awesome! Can you mention your project details in the Readme? (underneath Project List section)

where ?

2022-10-11 02:33 UTC, Greeshma2903 commented
[As mentioned here](https://github.com/Design-and-Code/Quick-projects/blob/95c2134d11566d78b50f24cd7d29cee6f1fec6fc/CONTRIBUTING.md?plain=1#L94), you can add it in the table under `reactJS` under [Projects List](https://github.com/Design-and-Code/Quick-projects#projects-list-) section in README.

2022-10-12 10:36 UTC, SumitKanth commented
@Greeshma2903 is it okii ? 👀 

![Screenshot (571)](https://user-images.githubusercontent.com/90907720/195319955-a6575617-482b-4667-9e5e-019e7ab7250a.png)

2022-10-12 11:19 UTC, Greeshma2903 commented
> @Greeshma2903 is it okii ? 👀
> 
> ![Screenshot (571)](https://user-images.githubusercontent.com/90907720/195319955-a6575617-482b-4667-9e5e-019e7ab7250a.png)

Yes

2022-10-12 17:27 UTC, SumitKanth commented
@Greeshma2903 can you review it

2022-10-13 16:34 UTC, Greeshma2903 requested changes

2022-10-13 17:02 UTC, Rajkumar-justcoder commented on README.md
> +=======
also here ig

2022-10-13 19:58 UTC, SumitKanth commented
@Greeshma2903  @Rajkumar-justcoder now ?

![Screenshot (574)](https://user-images.githubusercontent.com/90907720/195697180-0b37d34f-c32f-4d85-b571-ea9528ddcd9a.png)

2022-10-14 12:02 UTC, Greeshma2903 commented
> @Greeshma2903 @Rajkumar-justcoder now ?
> 
> ![Screenshot (574)](https://user-images.githubusercontent.com/90907720/195697180-0b37d34f-c32f-4d85-b571-ea9528ddcd9a.png)
Yes.
Also, please add the project description to only one ReactJS table (the one below where other projects are mentioned). 

https://github.com/Design-and-Code/Quick-projects#reactjs

2022-10-14 13:27 UTC, SumitKanth commented
@Greeshma2903 now ?

![Screenshot (581)](https://user-images.githubusercontent.com/90907720/195858545-297d80e6-7c58-4d27-b4b8-3477f01ee7e1.png)

2022-10-15 15:46 UTC, Greeshma2903 commented
> @Greeshma2903 now ?
> 
> ![Screenshot (581)](https://user-images.githubusercontent.com/90907720/195858545-297d80e6-7c58-4d27-b4b8-3477f01ee7e1.png)

Umm, I can't see any changes 😅

2022-10-15 16:10 UTC, SumitKanth commented
@Greeshma2903 what to do 👀

2022-10-15 17:41 UTC, Greeshma2903 commented
I hope the changes are clear now 😅 I'll go ahead and _close_ this PR.

2022-10-15 17:41 UTC, closed without merging